name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint:
    name: Lint (Go, TS, Python)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install shellcheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: api/package.json
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install API deps
        working-directory: api
        run: npm ci
      - name: Install Python deps
        working-directory: tools
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
      - name: Run unified lint script
        run: ./scripts/lint.sh

  test:
    name: Tests (Go, TS, Python)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: api/package.json
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install API deps
        working-directory: api
        run: npm ci
      - name: Install Python deps
        working-directory: tools
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run unified test script
        run: ./scripts/test.sh
